import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import PageTransition from "@/components/PageTransition";
import Strairtransition from "@/components/strairtransition";

const inter = Inter({ subsets: ["latin"],
  weight:["100",'200','300','400','500','600','700','800'],
  variable:'--primary'
 });

export const metadata = {
  title: "portfolio",
  description: "Generated by ericsson",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header className= ""/>
        <Strairtransition/>
        <PageTransition>{children}</PageTransition>        
        </body>
    </html>
  );
}
